### ISSUE TITLE
A message delay problem

### ISSUE THREAD

**Issue by moriyalb** [mqttjs/mqtt-connection#12]
mqtt-connection version 3.0.0

in connection.js
 this.write(opts)  
and parseStream.js
 function process(chunk, enc, cb) {

A message cost a 100ms delay , I don't know why. the network is very good and no problem.
how can I debug this ?

**Comment by mcollina** [comment]
How big is the message?

**Comment by moriyalb** [comment]
Sorry, I think it just my problem.
