### ISSUE TITLE
5.0 wrong options set on connack

### ISSUE THREAD

**Issue by friesendrywall** [mqttjs/mqtt-connection#26]
From a client perspective:

Regardless of options passed to initial connection, subsequent calls parse as v4, because ```that.setOptions(connectPacket)``` in connection.js sets option to returned packet from connack, which doesn't contain a ```protocolVersion```

**Comment by friesendrywall** [comment]
One hack workaround is this:

```
conn.on('connack', function (packet) {
    packet.protocolVersion = 5;
    conn.setOptions(packet);
});
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by friesendrywall** [comment]
Note: this fix requires param to be passed at client creation like

`      
const client = mqttCon(ws, {
        protocolVersion: 5
      });
`
