### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by silentMood** [mqttjs/mqtt-connection#3]
How about make mqtt-connection support the generator. I think it will make development going more smooth.

**Comment by mcollina** [comment]
This module is a compatibility module for an older (event-based) API. The "general use" modules are http://npm.im/mqtt-packet and http://npm.im/mqtt.

You can easily build your own using mqtt-packet and generators, we can add a link here if you want :).

**Comment by silentMood** [comment]
Because I notice that the mosca aslo use this to wrap stream create connection when a req comes in. So I get this idea out... ok, I get your point. I will add a generator polyfill to use it. Thanks for respond :)

**Comment by mcollina** [comment]
As soon as it is done, Mosca will move to mqtt-packet: see the https://github.com/mcollina/aedes project.

**Comment by silentMood** [comment]
ok... Maybe I should only use generator on the upper layer with mosca in my application for now. I will keep watching Aedes. Thanks for telling.
